spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo1?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: tongsuh
    password: qaz321
    #proxy-target-class属性值决定是基于JDK接口还是基于类的代理被创建。如果为true代表基于类的代理，如果为false代表基于JDK接口的代理。
  #aop:
   # proxy-target-class: true

#
#  devtools:
#    restart:
#      enabled: true
#      additional-paths: src/main/java
#      exclude: WEB-INF/**
#  freemarker:
#    cache: false

mybatis-plus:
  #配置扫描xml
  mapper-locations: classpath*:/mapper/**Mapper.xml
  #配置实体扫描类
  type-aliases-package: com.example.server.mapper
  global-config:
    db-config:
      id-type: auto

server:
  port: 8081


